### PR TITLE
Csharp

### PR DESCRIPTION
**Pull request by heedfull**
Really enjoying the book, and wanted to work through it in c#. Not sure if you're interested in having a multi language kata, but thought you may. I'm happy to update the readme with more details on running the c# part, if this is something you want to add in.

The only major changes besides making it compile for c# are around the draw method. I've decided to add a colour for the air tiles as clearing down the game board and redrawing the whole thing made the game flicker.

### CODE REVIEW

**Comment by thedrlambda** [comment]
Hi Edwin, thank you for the kind words, and for making this! This is a great start and I definitely want to use it for something, but I am completely swamped at the moment, so I won't have time to merge this request for a little while. Just to let you know to be patient 🙂 

A few things I am thinking off the top of my head:
- This repo is sort of special because the commits directly align with the book, and everything is tagged in the "future" as seen from master. I don't think we need to also make the c# for all the steps or tags. Therefore I am considering whether this should be a different repo, and then link to it in this repo's readme 🤔 
- If we should do C# -- and I think we should -- then we should also follow the C# naming convention and capitalize all the methods.
- I notice that creating a graphics-object is simpler here than in TS which means there is one extract method in the book that won't show up here. You say we are having to draw the air which is also a bit different than the book. Maybe we can solve both by immediately after "CreateGraphics" drawing a white rectangle across the entire component. What do you think?

**Comment by heedfull** [comment]
Hi Christian, 

No worries about being swamped. I totally understand. Glad you shared your thoughts with me.

I was going to work through the problem and am happy to commit my changes to the solution branch, so they are "in the future". I had contemplated rewriting git history so that the same changes in the c# went into the existing commits, but want to run this by you before attempting it.

I'm happy to follow C# conventions. I initially didn't want to make too many changes, but using the original names does put my teeth slightly on edge. I'll push these changes.

re:graphics What you describe is similar to my initial approach. In winforms there is an option to clear the graphics. Maybe it's the way I'm doing it (I've not worked with graphics like this before) but it caused the game to flicker a lot. I'll try the large white box and see if it improves things. It would be good to stick as close to the examples in your book if it's possible. I guess I could leave the flicker in there and maybe someone else might be able to fix it.

The only other worry I had was that winforms is tied to windows and you lose the cross platform that you can now get with .NET. There is now a cross platform GUI, that I might take a look at.
[https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/)

**Comment by thedrlambda** [comment]
I didn't mean to close this, but I needed to fix something on master. I have not forgotten about you! :)

**Comment by thedrlambda** [comment]
Hi again Edwin, sorry for the long delay, as I said: Busy. Would you mind putting your C# implementation in a repo on your own profile, then I will add a section in the readme for other languages and link to it. I think this is the solution that scales best if other people want to port it to other languages as well, since they (and you) won't have to maintain the "solution" branch, which is quite a lot of work. :) Thanks again for making it 🙏

**Pull request closed without merging**
